# Generated by Django 5.0.4 on 2024-04-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customuser_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='User_ID',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Password',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='User_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
